GitHub actions
aran-nakayama/laravel8-vue pull request #11
Opened 2021-03-25 02:30 UTC by aran-nakayama

テストを開発中なのですが、一つ困っていることがあります。
リモートではテストが通るのですが、Actionsでは通りません。

下書きですが一旦レビューよろしくお願いいたします。

2021-03-25 05:53 UTC, T-Kiyama approved these changes
@aran-nakayama 
一度、"env.testing"に".env"にあるAPP_KEYをそのままコピペして試していただきたいです...!

2021-03-25 05:53 UTC, T-Kiyama commented on laravel/.env.testing
>  APP_KEY=
@aran-nakayama 
一度、"env.testing"に".env"にあるAPP_KEYをそのままコピペして保存後、pushを試していただきたいです...!

2021-03-25 06:22 UTC, T-Kiyama requested changes
間違ってapproveしちゃってたので付け直しておきます...!

2021-03-29 02:23 UTC, aran-nakayama commented
レビューありがとうございました。
ローカル環境ではテストが通っているので、一旦マージしておきます。

2021-03-29 02:24 UTC, merged